name: Deploy development branch to GitHub Pages

on:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
        with:
          ref: "dev"
      - name: Install, build, and upload your site output
        uses: withastro/action@v2
        with:
          path: "frontend"
          package-manager: pnpm@latest
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEV_DEPLOY_TOKEN }}
          external_repository: lyonsyonii/dev.rust-quest
          publish_branch: gh-pages  # default: gh-pages
