name: Update PR description

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  update-pr-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: octue/generate-pull-request-description@1.0.0.beta-2
        id: pr-description
        with:
          pull_request_url: ${{ github.event.pull_request.url }}
          api_token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update pull request body
        uses: riskledger/update-pr-description@v2
        with:
          body: ${{ steps.pr-description.outputs.pull_request_description }}
          token: ${{ secrets.GITHUB_TOKEN }}

# "FEA": "### New features",
# "ENH": "### Enhancements",
# "FIX": "### Fixes",
# "OPS": "### Operations",
# "DEP": "### Dependencies",
# "REF": "### Refactoring",
# "TST": "### Testing",
# "REV": "### Reversions",
# "CHO": "### Chores",
# "STY": "### Style",
# "MRG": OTHER_SECTION_HEADING,
# "WIP": OTHER_SECTION_HEADING,
# "DOC": OTHER_SECTION_HEADING,